// --- BARGE BOOT SCRIPT (barge.ks) ---
// This script runs automatically on the Barge's CPU.

CLEARSCREEN.
PRINT "--- ASDS BARGE BOOT SYSTEM ACTIVE ---".

// 1. EXTEND PHYSICS RANGE (Allows ships to "see" barge from 2500km)
FUNCTION SetPhysicsRange {
    PARAMETER d.
    SET SHIP:LOADDISTANCE:FLYING:UNLOAD TO d. SET SHIP:LOADDISTANCE:FLYING:LOAD TO d*0.95.
    SET SHIP:LOADDISTANCE:SUBORBITAL:UNLOAD TO d. SET SHIP:LOADDISTANCE:SUBORBITAL:LOAD TO d*0.95.
    SET SHIP:LOADDISTANCE:ORBIT:UNLOAD TO d. SET SHIP:LOADDISTANCE:ORBIT:LOAD TO d*0.95.
    SET SHIP:LOADDISTANCE:LANDED:UNLOAD TO d. SET SHIP:LOADDISTANCE:LANDED:LOAD TO d*0.95.
    
    SET KUNIVERSE:DEFAULTLOADDISTANCE:FLYING:UNLOAD TO d.
    SET KUNIVERSE:DEFAULTLOADDISTANCE:FLYING:LOAD TO d*0.95.
    SET KUNIVERSE:DEFAULTLOADDISTANCE:LANDED:UNLOAD TO d.
    SET KUNIVERSE:DEFAULTLOADDISTANCE:LANDED:LOAD TO d*0.95.
    
    HUDTEXT("BARGE PHYSICS EXTENDED: " + (d/1000) + "km", 5, 2, 30, CYAN, FALSE).
}

SetPhysicsRange(2500000). // 2500km (Max Stability)

// 2. PERSISTENT GPS HEARTBEAT
UNTIL FALSE {
    PRINT "Barge Location: " + ROUND(SHIP:GEOPOSITION:LAT, 4) + ", " + ROUND(SHIP:GEOPOSITION:LNG, 4) + "   " AT(0, 5).
    PRINT "Status: READY FOR RECOVERY" AT(0, 6).
    
    WAIT 10. // Low impact loop
}
